export enum SocketListenerEnum {
  NEW_APPOINTMENT = 'NEW_APPOINTMENT',
  UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT',
  UPDATE_APPOINTMENT_LIST = 'UPDATE_APPOINTMENT_LIST',

  PARTICIPANTS_CHANGED = 'PARTICIPANTS_CHANGED',
}

export enum SocketSubscribeEnum {
  SUBSCRIBE_UPDATE_APPOINTMENT = 'SUBSCRIBE_UPDATE_APPOINTMENT',
  SUBSCRIBE_UPDATE_LIST_APPOINTMENT = 'SUBSCRIBE_UPDATE_LIST_APPOINTMENT',
  SUBSCRIBE_PARTICIPANTS = 'SUBSCRIBE_PARTICIPANTS',
}
