export const institutionTabEnum = {
  UNIT_PANEL: 'UNIT_PANEL',
  DATA_TAB: 'DATA_TAB',
  LEARNING_TAB: 'LEARNING_TAB',
  USERS_TAB: 'USERS_TAB',
  LINK_TAB: 'LINK_TAB',
  HEALTH_UNITS_TAB: 'HEALTH_UNITS_TAB',
  SETTINGS_TAB: 'SETTINGS_TAB',
  REPORTS_TAB: 'REPORTS_TAB',
  IMPORT_TAB: 'IMPORT_TAB',
}
