export enum EventRecordsType {
  EXAM = 'EXAM',
  MEDICAL_RECORDS = 'MEDICAL_RECORDS',
  SICK_NOTE = 'SICK_NOTE',
  REPORTS = 'REPORTS',
  ATTACHMENTS = 'ATTACHMENTS',
  PRESCRIPTION = 'PRESCRIPTION',
  SPECIAL_PRESCRIPTION = 'SPECIAL_PRESCRIPTION',
  DIAGNOSE = 'DIAGNOSE',
}
