export const Permissions = {
  ADD_USER: 'ADD_USER',
  ADD_USERS_BY_BATCH: 'ADD_USERS_BY_BATCH',
  ADD_RESPONSABLE: 'ADD_RESPONSABLE',
  VIEW_USERS: 'VIEW_USERS',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_HEALTH_LEADER: 'UPDATE_HEALTH_LEADER',
  MANAGE_ROLE: 'MANAGE_ROLE',
  EXPORT_USERS: 'EXPORT_USERS',

  ADD_APPOINTMENT: 'ADD_APPOINTMENT',
  MANAGE_APPOINTMENT: 'MANAGE_APPOINTMENT',
  VIEW_APPOINTMENT: 'VIEW_APPOINTMENT',
  VIEW_OTHER_APPOINTMENT: 'VIEW_OTHER_APPOINTMENT',
  VIEW_FACULTATIVE_USERS_APPOINTMENTS_RECORDS: 'VIEW_FACULTATIVE_USERS_APPOINTMENTS_RECORDS',

  MANAGE_HEALTH_HISTORY: 'MANAGE_HEALTH_HISTORY',
  APPROVE_MEDICINE: 'APPROVE_MEDICINE',
  MANAGE_OTHER_HEALTH_HISTORY: 'MANAGE_OTHER_HEALTH_HISTORY',

  VIEW_PROFILES: 'VIEW_PROFILES',
  MANAGE_PROFILES: 'MANAGE_PROFILES',

  MANAGE_HEALTH_UNIT: 'MANAGE_HEALTH_UNIT',
  VIEW_HEALTH_UNIT: 'VIEW_HEALTH_UNIT',

  MANAGE_ORGANIZATION: 'MANAGE_ORGANIZATION',
  EDIT_OWN_ORGANIZATION: 'EDIT_OWN_ORGANIZATION',
  VIEW_ORGANIZATIONS: 'VIEW_ORGANIZATIONS',

  ADD_INDICATION: 'ADD_INDICATION',
  MANAGE_INDICATION: 'MANAGE_INDICATION',
  VIEW_INDICATION: 'VIEW_INDICATION',

  MANAGE_COURSE: 'MANAGE_COURSE',

  MANAGE_MENTAL_HEALTH_PLAN: 'MANAGE_MENTAL_HEALTH_PLAN',
  VIEW_MENTAL_HEALTH_PLAN: 'VIEW_MENTAL_HEALTH_PLAN',
  WRITE_MENTAL_HEALTH_COMMENT: 'WRITE_MENTAL_HEALTH_COMMENT',

  MANAGE_INTERN_RECORD: 'MANAGE_INTERN_RECORD',
  VIEW_INTERN_RECORD: 'VIEW_INTERN_RECORD',

  MANAGE_EXTERNAL_RECORD: 'MANAGE_EXTERNAL_RECORD',
  VIEW_EXTERNAL_RECORD: 'VIEW_EXTERNAL_RECORD',

  READ_RECORDS: 'READ_RECORDS',
  MANAGE_DOCUMENT_MENTAL_HEALTH_RECORDS: 'MANAGE_DOCUMENT_MENTAL_HEALTH_RECORDS',

  MANAGE_BEHAVIOUR: 'MANAGE_BEHAVIOUR',
  VIEW_BEHAVIOUR: 'VIEW_BEHAVIOUR',

  MANAGE_CHALLENGE: 'MANAGE_CHALLENGE',
  VIEW_CHALLENGE: 'VIEW_CHALLENGE',

  MANAGE_INTEREST_AREA: 'MANAGE_INTEREST_AREA',
  LIST_INTEREST_AREA: 'LIST_INTEREST_AREA',

  MANAGE_MEDICAL_REPORT: 'MANAGE_MEDICAL_REPORT',
  CAN_VIEW_MEDICAL_REPORT: 'CAN_VIEW_MEDICAL_REPORT',

  MANAGE_MEDICAL_ANALYSIS: 'MANAGE_MEDICAL_ANALYSIS',
  CAN_VIEW_MEDICAL_ANALYSIS: 'CAN_VIEW_MEDICAL_ANALYSIS',

  MANAGE_REQUESTED_ANALYSIS: 'MANAGE_REQUESTED_ANALYSIS',
  CAN_VIEW_REQUESTED_ANALYSIS: 'CAN_VIEW_REQUESTED_ANALYSIS',
}
