export enum UserViewConfigKeys {
  RESPONSIBLE = 'RESPONSIBLE',
  CHILD = 'CHILD',
  PSYCHO = 'PSYCHO',
  CAREGIVER = 'CAREGIVER',
  COLLABORATOR = 'COLLABORATOR',
  NO_PERMISSION = 'NO_PERMISSION',
}
