export enum ActivationStatusEnum {
  INSERT_EMAIL = 'INSERT_EMAIL',
  INSERT_PHONE = 'INSERT_PHONE',
  VALIDATE_EMAIL = 'VALIDATE_EMAIL',
  VALIDATE_PHONE = 'VALIDATE_PHONE',
  ACTIVE = 'ACTIVE',
  MISSING_PASSWORD = 'MISSING_PASSWORD',
  ACTIVATING = 'ACTIVATING',
}
