export const PENDING_ACTIONS_TYPES = {
  GENERAL_DATA: 'GENERAL_DATA',
  HEALTH_HISTORY: 'HEALTH_HISTORY',
} as const

export const PENDING_ACTIONS_SUB_TYPES = {
  DEPENDENT_1: 'DEPENDENT_1',
  DEPENDENT_2: 'DEPENDENT_2',
  SELF: 'SELF',
} as const
