export enum PedagogicalRecordType {
  DIFFICULTIES_OR_CHALLENGES = 'DIFFICULTIES_OR_CHALLENGES',
  BEHAVIORS = 'BEHAVIORS',
  AREAS_OF_INTEREST = 'AREAS_OF_INTEREST',
  EXTERNAL_RECORDS = 'EXTERNAL_RECORDS',
  COALA_RECORDS = 'COALA_RECORDS',
}
